version: '3.9'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    tty: true
    command: tail -f /dev/null